### ISSUE TITLE
why install libwww-perl (LWP) ?

### ISSUE THREAD

**Issue by melezhik** [chef-cookbooks/perl#26]
Hi guys! First of all, good job! Thanks a lot lot this cookbook.

I have noticed that perl-libwww-perl  gets installed by default for many OS, I wonder WHAT the reason to install it? I know that for most cases it gets installed as pre-recompiled native package by OS related package manager , not cpan, but:

* it still time consuming
* it "pollutes" system wide perl environment with a lot of dependencies ( please take a look at https://metacpan.org/pod/LWP ) - which sometimes is not good. As you know lwp is quite heave, this is one of the reason for it has so many lightweight alternatives ( HTTP:Tiny , etc ) 

```
case node['platform_family']
when 'rhel', 'fedora'
  default['perl']['packages'] = %w(perl perl-libwww-perl perl-CPAN)

  case node['platform_version'].to_i
  when 5
    default['perl']['packages'] = %w(perl perl-libwww-perl)
  else
    default['perl']['packages'] = %w(perl perl-libwww-perl perl-CPAN)
  end

when 'debian'
  default['perl']['packages'] = %w(perl libperl-dev libwww-perl)
when 'arch'
  default['perl']['packages'] = %w(perl perl-libwww)
when 'omnios'
  default['perl']['packages'] = %w(perl)
when 'windows'
  default['perl']['maj_version'] = '5'
  default['perl']['min_version'] = '16'
  default['perl']['sub_version'] = '1.1'

  case node['kernel']['machine'].to_s
  when 'x86_64'
    default['perl']['bitness'] = '64bit'
  else
    default['perl']['bitness'] = '32bit'
  end

else
  default['perl']['packages'] = %w(perl libperl-dev)
end
```

**Comment by tas50** [comment]
I removed libwww-perl from the 3.0 release which is up on Supermarket now
