### ISSUE TITLE
depends 'windows' causing dependancy failure in vagrant with centos

### ISSUE THREAD

**Issue by quixand** [chef-cookbooks/perl#28]
using master
commit 4a4cafb57df41b68efb81f919a48798adf1f1f74
Author: Tim Smith <...>
Date:   Fri Apr 29 21:09:16 2016 -0700

[vagrant@localhost ~]$ chef-solo -v
Chef: 12.10.24

$ vagrant -v
Vagrant 1.8.1
on OSX 10.9.5

### Scenario:
vagrant up using 
`Vagrant.configure(2) do |config|

    config.vm.box = "boxcutter/centos72"

    config.vm.define "scriptsVM"
    config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 2
    end

    config.vm.network :forwarded_port, guest: 80, host: 9999
    config.vm.network :forwarded_port, guest: 443, host: 9997
    config.ssh.forward_agent = true

    config.vm.provision :chef_solo do |chef|
        chef.version = "12.10.24"
        chef.channel = "stable"
        chef.cookbooks_path = ["cookbooks"]
        chef.add_recipe "perl"
        chef.add_recipe "perl::cpan-modules"
	end
end`

### Steps to Reproduce:
It seems the module dependency on line 15 of metadata.rb is causing chef to exit during the vagrant build. If I comment it out the perl build completes ok

### Expected Result:
clean process exit, I don't understand what this windows module is, but I don't need it apparently.

### Actual Result:
vagrant output
`==> TacticalScriptsVM: Installing Cookbook Gems:
==> TacticalScriptsVM: Compiling Cookbooks...
==> TacticalScriptsVM: 
==> TacticalScriptsVM: Running handlers:
==> TacticalScriptsVM: [2016-06-28T14:32:53+00:00] ERROR: Running exception handlers
==> TacticalScriptsVM: Running handlers complete
==> TacticalScriptsVM: [2016-06-28T14:32:53+00:00] ERROR: Exception handlers complete
==> TacticalScriptsVM: Chef Client failed. 0 resources updated in 03 seconds
==> TacticalScriptsVM: [2016-06-28T14:32:53+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> TacticalScriptsVM: [2016-06-28T14:32:53+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> TacticalScriptsVM: [2016-06-28T14:32:53+00:00] ERROR: Cookbook windows not found. If you're loading windows from another cookbook, make sure you configure the dependency in your metadata
==> TacticalScriptsVM: [2016-06-28T14:32:53+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.`

stack trace
`Generated at 2016-06-28 14:32:53 +0000
Chef::Exceptions::CookbookNotFound: Cookbook windows not found. If you're loading windows from another cookbook, make sure you configure the dependency in your metadata
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/cookbook/cookbook_collection.rb:39:in `block in initialize'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.15.1/lib/ohai/mash.rb:77:in `yield'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.15.1/lib/ohai/mash.rb:77:in `default'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.15.1/lib/ohai/mash.rb:77:in `default'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/run_context/cookbook_compiler.rb:276:in `[]'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/run_context/cookbook_compiler.rb:276:in `each_cookbook_dep'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/run_context/cookbook_compiler.rb:255:in `add_cookbook_with_deps'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/run_context/cookbook_compiler.rb:256:in `block in add_cookbook_with_deps'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/run_context/cookbook_compiler.rb:277:in `each'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/run_context/cookbook_compiler.rb:277:in `each_cookbook_dep'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/run_context/cookbook_compiler.rb:255:in `add_cookbook_with_deps'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/run_context/cookbook_compiler.rb:88:in `block in cookbook_order'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/run_context/cookbook_compiler.rb:86:in `each'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/run_context/cookbook_compiler.rb:86:in `cookbook_order'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/run_context/cookbook_compiler.rb:98:in `compile_libraries'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/run_context/cookbook_compiler.rb:71:in `compile'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/run_context.rb:176:in `load'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/policy_builder/expand_node_object.rb:97:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/client.rb:508:in `setup_run_context'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/client.rb:278:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application.rb:285:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application.rb:273:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application.rb:273:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application.rb:238:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application.rb:226:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application/solo.rb:301:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application/solo.rb:290:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application/solo.rb:290:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application/solo.rb:269:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/lib/chef/application.rb:58:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.10.24/bin/chef-solo:25:in `<top (required)>'
/bin/chef-solo:51:in `load'
/bin/chef-solo:51:in `<main>'
/var/chef/cache/chef-stacktrace.out (END)`

**Comment by tas50** [comment]
You'll see this sort of issue with Vagrant since you're not actually fetching the deps you need to test the cookbook.  I'd highly recommend testing with Test Kitchen where Berkshelf will handle fetching all your deps from the Supermarket.
